import React from 'react';
import { Card, CardContent } from '@/components/common/Card';

export default function TermsPage() {
    return (
        <div className="min-h-screen py-16 lg:py-24">
            <div className="container max-w-4xl">
                {/* Header */}
                <div className="text-center mb-12">
                    <span className="text-primary font-mono text-sm mb-2 block">// LEGAL</span>
                    <h1 className="text-4xl lg:text-5xl font-bold text-foreground mb-4">
                        Terms of Service
                    </h1>
                    <p className="text-muted-foreground">
                        Last updated: December 20, 2024
                    </p>
                </div>

                <Card variant="glass">
                    <CardContent className="p-8 prose prose-invert max-w-none">
                        <section className="mb-8">
                            <h2 className="text-xl font-bold text-foreground mb-4">1. Acceptance of Terms</h2>
                            <p className="text-muted-foreground mb-4">
                                By accessing or using The Orchestra Studio ("Service"), you agree to be bound by these
                                Terms of Service ("Terms"). If you disagree with any part of the terms, you may not
                                access the Service.
                            </p>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-xl font-bold text-foreground mb-4">2. Description of Service</h2>
                            <p className="text-muted-foreground mb-4">
                                The Orchestra Studio is an AI-powered platform that enables users to collaborate with
                                specialized AI agents to generate, critique, refine, and present ideas. The Service
                                includes web application access, API access (for eligible plans), and related features.
                            </p>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-xl font-bold text-foreground mb-4">3. User Accounts</h2>
                            <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                                <li>You must be at least 18 years old to use this Service</li>
                                <li>You are responsible for maintaining the security of your account</li>
                                <li>You must provide accurate and complete registration information</li>
                                <li>You may not share your account credentials with others</li>
                            </ul>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-xl font-bold text-foreground mb-4">4. Acceptable Use</h2>
                            <p className="text-muted-foreground mb-4">You agree NOT to use the Service to:</p>
                            <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                                <li>Generate illegal, harmful, or offensive content</li>
                                <li>Violate any applicable laws or regulations</li>
                                <li>Infringe on intellectual property rights of others</li>
                                <li>Attempt to gain unauthorized access to the Service</li>
                                <li>Interfere with or disrupt the Service</li>
                                <li>Use automated systems to abuse the Service</li>
                            </ul>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-xl font-bold text-foreground mb-4">5. Intellectual Property</h2>
                            <h3 className="text-lg font-semibold text-foreground mb-2">Your Content</h3>
                            <p className="text-muted-foreground mb-4">
                                You retain ownership of the content you submit to the Service. By using the Service,
                                you grant us a license to process your content to provide the Service.
                            </p>
                            <h3 className="text-lg font-semibold text-foreground mb-2">AI-Generated Output</h3>
                            <p className="text-muted-foreground mb-4">
                                Output generated by our AI agents is provided to you under a license that allows
                                commercial use, subject to these Terms.
                            </p>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-xl font-bold text-foreground mb-4">6. Payment & Subscriptions</h2>
                            <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                                <li>Paid subscriptions are billed in advance on a monthly or yearly basis</li>
                                <li>All fees are in Indian Rupees (₹) unless otherwise stated</li>
                                <li>You can cancel your subscription at any time</li>
                                <li>Refunds are provided as per our Refund Policy</li>
                                <li>Prices may change with 30 days notice</li>
                            </ul>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-xl font-bold text-foreground mb-4">7. Service Level & Availability</h2>
                            <p className="text-muted-foreground mb-4">
                                We strive to maintain 99.9% uptime for the Service. However, we do not guarantee
                                uninterrupted access. Enterprise customers receive SLA guarantees as specified in
                                their service agreement.
                            </p>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-xl font-bold text-foreground mb-4">8. Limitation of Liability</h2>
                            <p className="text-muted-foreground mb-4">
                                TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE ORCHESTRA STUDIO SHALL NOT BE LIABLE FOR
                                ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, OR ANY LOSS
                                OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY.
                            </p>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-xl font-bold text-foreground mb-4">9. Termination</h2>
                            <p className="text-muted-foreground mb-4">
                                We may terminate or suspend your account immediately, without prior notice, for
                                conduct that we believe violates these Terms or is harmful to other users, us,
                                or third parties.
                            </p>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-xl font-bold text-foreground mb-4">10. Governing Law</h2>
                            <p className="text-muted-foreground mb-4">
                                These Terms shall be governed by and construed in accordance with the laws of India.
                                Any disputes shall be subject to the exclusive jurisdiction of the courts in
                                Bangalore, Karnataka.
                            </p>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-xl font-bold text-foreground mb-4">11. Contact</h2>
                            <p className="text-muted-foreground">
                                For questions about these Terms, please contact us at:
                            </p>
                            <p className="text-primary mt-2">legal@theorchestrastudio.com</p>
                        </section>
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}
